configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzdiMGM0ODdmY2MyZTg3NzFjM2Y5OGM5M2YxYThkMGJkY2NhMTkyYmU1MjMzNDc2MjY3N2VjZjVkYjZmZjc1ZTQ3NjU0NTQzMjdjYTEyMDE2ZTcyNWFjYzk0ZmVlM2E3NDMwNjdhZjE0Zjk1ZjU2ZjFiYjdmZjFjMTMxMGFmNjU=
