# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
        - USER

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZmIyYTJmODg3ZGI0NWY5M2VjMGEwOGE4YTIxYmNiMTA1MmYyN2UzZjNhNTk3N2RlMWE2YjhiMTU0NTkyMTllOTEyNjc0ZWNlNTY2NmY4NGU2ZGFjODg2ZmM2NjUxNGNkMDBkZDFkNGM2MTIzODhkNzdlM2U5OTBkOWNmYWZjYTI=
